CREATE TABLE DOWNLOAD_TASK (
 ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 URL VARCHAR(255), 
 DEST VARCHAR(255), 
 TOTAL_SIZE BIGINT, 
 DOWNLOADED_SIZE BIGINT, 
 CREATE_TIME TIMESTAMP, 
 FINISH_TIME TIMESTAMP, 
 LAST_UPDATE TIMESTAMP, 
 STATUS VARCHAR(50), 
 RESUMABLE BIGINT  DEFAULT 1 , 
 EPISODE_ID VARCHAR(30), 
 INDEX BIGINT DEFAULT 0,
 PRIMARY KEY (ID));
