CREATE TABLE EPISODE (
 ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 EPISODE_ID VARCHAR(30), 
 PROGRAM_ID VARCHAR(30), 
 TITLE VARCHAR(100), 
 HD_URL VARCHAR(3000), 
 SD_URL VARCHAR(3000), 
 "TYPE" VARCHAR(30), 
 STATUS VARCHAR(20),
 INDEX BIGINT DEFAULT 0,
 PRIMARY KEY (ID));
